version: '3.5'

services:
  db:
    image: postgis/postgis:13-3.0
    restart: always
    shm_size: 4gb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: YOURPASSWORD
      POSTGRES_USER: YOURUSER
      POSTGRES_DB: DBNAME
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./input:/home/input


